sudo : required
language: generic
services:
  - docker
before_install:
  - docker build -t nmodem2k/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true nmodem2k/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app : "frontend"
  env : "Frontend-env"
  bucket_name : "elasticbeanstalk-ap-south-1-875200346462"
  bucket_path: "frontend"
  on :
    branch: "main"

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY